# Generated by Django 3.0 on 2021-08-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_auto_20210817_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
    ]
