# Generated by Django 3.0 on 2021-08-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_jugador_preguntasrespondidas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreguntasRespondidas',
            new_name='PreguntasRespondida',
        ),
    ]
