# Generated by Django 3.0 on 2021-08-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_auto_20210825_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondida',
            name='jugadorP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='preguntas.Jugador'),
        ),
    ]
